repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-ast
    - id: check-yaml
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: "5.12.0"
  hooks:
    - id: isort
      args: [--line-length=120]
- repo: https://github.com/pycqa/flake8
  rev:  "6.1.0"
  hooks:
    - id: flake8
      args: [--max-line-length=120, --ignore=E252]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.6
  hooks:
    - id: shellcheck
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true

